# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: touch .nojekyll
      working-directory: ./dist
    - run: git init
      working-directory: ./dist
    - run: git config user.name github-actions
      working-directory: ./dist
    - run: git config user.email github-actions@github.com
      working-directory: ./dist
    - run: git checkout -b gh-pages
      working-directory: ./dist
    - run: git add -A
      working-directory: ./dist
    - run: git commit -m 'deploy'
      working-directory: ./dist
    - run: git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
      working-directory: ./dist
